### ISSUE TITLE
Handle case where episode has hit public feed prior to delegated delivery upload/upload

### ISSUE THREAD

**Issue by svevang** [PRX/feeder.prx.org#1080]
We currently have a hybrid API/RSS control of episodes. In the case where an episode as already hit the public feed, the Apple rss poller takes over updates to the episode models, and any subsequent updates to the episode via the API returns a 409.

In the case of episode updates, if an episode is returning 409s, that indicates that the episode is already managed by apple.
 We do have some code for handling 404s, https://github.com/PRX/feeder.prx.org/blob/main/app/models/apple/api.rb#L209-L213
We can extend that to "ignore" the 409s and carry on the publishing routine.

- [ ] ignore episode update 409s for already published episodes
- [ ] log out some warnings

**Comment by kookster** [comment]
here's an example error response and backtrace:
```
Error performing PublishAppleJob (Job ID: 01ed1757-4558-4238-a915-66390b47f26c) from Shoryuken(dc51b3fd_prod_feeder_publishing) in 4550.5ms: Apple::ApiError (
[
    {
        "request_metadata": {
            "apple_episode_id": "1000667943312",
            "guid": "prx_25_025f9e65-6631-4120-a9e0-a20b80edc5aa"
        },
        "api_parameters": {
            "data": {
                "type": "episodes",
                "attributes": {
                    "title": "IN THIS MONOLOGUE: THE JABER TRIFECTA | A Point in the Sea + Gaza’s Dreams ",
                    "originalReleaseDate": "2024-09-03T06:00:00Z",
                    "description": "<p>“Before, you could count how many buildings they destroyed. Now, you count how many buildings they <strong><em>didn’t</em></strong> destroy” — Tarneem Jaber</p><p>Tarneem (19 yrs old)  was starting her first week of med school on October 7th. Ahmad (21 yrs old) was in his third year of dental school with only two remaining. Hamza (24 yrs old) was supposed to graduate this June: He was a volunteer at Al-Shifa until it was obliterated.</p><p>The three siblings survived the destruction of their home, food shortages, a long journey to the border, and finding an apartment to rent in Cairo, Egypt. Only a few weeks later they were doing an interview on zoom with a Canadian for a feminist podcast they’d never heard of, telling the story of what they lived and what goes on for the loved ones they left behind.</p><p>Each of the Jaber siblings chooses a monologue to read: Hamza reads #30: Yasmeen Abu Amer. Ahmad reads #8: Ehab Elayan. Tarneem reads #13: Reema El Sadi. \"We relate to every single word in this monologue,\" Tarneem says.</p><p>\"But this war, is worse than anything we lived before.\"</p><p><a href=\"https://gofund.me/854be259\"><strong>Support them to complete their mother's parting wish: to finish their education. Thrust into complete independence and faced with international student fees and paying over again for years they already completed, these three brilliant students need your help to fix problems they never should have had to face. </strong></a><strong>Please follow our link: https://gofund.me/854be259</strong></p>",
                    "websiteUrl": "https://play.prx.org/listen?ge=prx_25_025f9e65-6631-4120-a9e0-a20b80edc5aa&uf=http%3A%2F%2Ffeeds.theheartradio.org%2FTheHeartRadio",
                    "explicit": false,
                    "episodeNumber": 5,
                    "seasonNumber": 18,
                    "episodeType": "FULL",
                    "appleHostedAudioIsSubscriberOnly": true
                },
                "id": "1000667943312"
            }
        },
        "api_url": "https://api.podcastsconnect.apple.com/v1/episodes/1000667943312",
        "api_response": {
            "ok": false,
            "err": true,
            "val": {
                "data": {
                    "body": {
                        "errors": [
                            {
                                "id": "faf7152a-d5b4-4fb7-b104-0861df5f4ca3",
                                "status": "409",
                                "code": "ENTITY_ERROR.ATTRIBUTE.INVALID",
                                "title": "The provided entity includes an attribute with an invalid value",
                                "detail": "episodeType should not be present",
                                "source": {
                                    "pointer": "/data/attributes/episodeType"
                                }
                            },
                            {
                                "id": "c91d2398-02f6-4adf-89ac-c675140f7983",
                                "status": "409",
                                "code": "ENTITY_ERROR.ATTRIBUTE.INVALID",
                                "title": "The provided entity includes an attribute with an invalid value",
                                "detail": "episodeNumber should not be present",
                                "source": {
                                    "pointer": "/data/attributes/episodeNumber"
                                }
                            },
                            {
                                "id": "f9fa7f54-f205-4269-a3d0-08719092b835",
                                "status": "409",
                                "code": "ENTITY_ERROR.ATTRIBUTE.INVALID",
                                "title": "The provided entity includes an attribute with an invalid value",
                                "detail": "seasonNumber should not be present",
                                "source": {
                                    "pointer": "/data/attributes/seasonNumber"
                                }
                            },
                            {
                                "id": "e6183906-6c82-4970-b4cc-42a19cda460a",
                                "status": "409",
                                "code": "ENTITY_ERROR.ATTRIBUTE.INVALID",
                                "title": "The provided entity includes an attribute with an invalid value",
                                "detail": "originalReleaseDate should not be present",
                                "source": {
                                    "pointer": "/data/attributes/originalReleaseDate"
                                }
                            },
                            {
                                "id": "d7fa2d29-95bc-4c4e-913c-d50322e2d906",
                                "status": "409",
                                "code": "ENTITY_ERROR.ATTRIBUTE.INVALID",
                                "title": "The provided entity includes an attribute with an invalid value",
                                "detail": "description should not be present",
                                "source": {
                                    "pointer": "/data/attributes/description"
                                }
                            },
                            {
                                "id": "3420c25d-1917-4114-ae14-2a495b17a371",
                                "status": "409",
                                "code": "ENTITY_ERROR.ATTRIBUTE.INVALID",
                                "title": "The provided entity includes an attribute with an invalid value",
                                "detail": "title should not be present",
                                "source": {
                                    "pointer": "/data/attributes/title"
                                }
                            },
                            {
                                "id": "b49b6b5b-fb95-4d56-b74c-9ef4cd3ccc5b",
                                "status": "409",
                                "code": "ENTITY_ERROR.ATTRIBUTE.INVALID",
                                "title": "The provided entity includes an attribute with an invalid value",
                                "detail": "websiteUrl should not be present",
                                "source": {
                                    "pointer": "/data/attributes/websiteUrl"
                                }
                            },
                            {
                                "id": "8eec8601-a22f-418c-a909-caf1e2fc1515",
                                "status": "409",
                                "code": "ENTITY_ERROR.ATTRIBUTE.INVALID",
                                "title": "The provided entity includes an attribute with an invalid value",
                                "detail": "explicit should not be present",
                                "source": {
                                    "pointer": "/data/attributes/explicit"
                                }
                            }
                        ]
                    },
                    "status": 409,
                    "context": "response"
                }
            },
            "_stack": "    at formatApiError (file:///var/task/api_response.js:36:12)\n    at file:///var/task/api.js:182:46\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
        }
    }
])

/app/app/models/apple/api.rb:276:in `raise_bridge_api_error'
/app/app/models/apple/api.rb:270:in `bridge_remote_and_retry!'
/app/app/models/apple/episode.rb:107:in `update_episodes'
/app/app/models/apple/publisher.rb:267:in `block in sync_episodes!'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/tagged_logging.rb:135:in `block in tagged'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/tagged_logging.rb:39:in `tagged'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/tagged_logging.rb:135:in `tagged'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/broadcast_logger.rb:240:in `method_missing'
/app/app/models/apple/publisher.rb:250:in `sync_episodes!'
/app/app/models/apple/publisher.rb:138:in `block (2 levels) in deliver_and_publish!'
/app/app/models/apple/publisher.rb:133:in `each'
/app/app/models/apple/publisher.rb:133:in `each_slice'
/app/app/models/apple/publisher.rb:133:in `block in deliver_and_publish!'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/tagged_logging.rb:135:in `block in tagged'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/tagged_logging.rb:39:in `tagged'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/tagged_logging.rb:135:in `tagged'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/broadcast_logger.rb:240:in `method_missing'
/app/app/models/apple/publisher.rb:132:in `deliver_and_publish!'
/app/app/models/apple/publisher.rb:125:in `publish!'
/app/app/jobs/publish_apple_job.rb:5:in `publish_to_apple'
/app/app/jobs/publish_apple_job.rb:14:in `perform'
/usr/local/bundle/gems/activejob-7.1.3.4/lib/active_job/execution.rb:69:in `block in _perform_job'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/usr/local/bundle/gems/newrelic_rpm-8.13.1/lib/new_relic/agent/instrumentation/active_job.rb:54:in `perform'
/usr/local/bundle/gems/newrelic_rpm-8.13.1/lib/new_relic/agent/instrumentation/active_job.rb:23:in `block (4 levels) in <main>'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `instance_exec'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
/usr/local/bundle/gems/i18n-1.14.5/lib/i18n.rb:346:in `with_locale'
/usr/local/bundle/gems/activejob-7.1.3.4/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `instance_exec'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/core_ext/time/zones.rb:65:in `use_zone'
/usr/local/bundle/gems/activejob-7.1.3.4/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `instance_exec'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:141:in `run_callbacks'
/usr/local/bundle/gems/activejob-7.1.3.4/lib/active_job/execution.rb:68:in `_perform_job'
/usr/local/bundle/gems/activejob-7.1.3.4/lib/active_job/instrumentation.rb:32:in `_perform_job'
/usr/local/bundle/gems/activejob-7.1.3.4/lib/active_job/execution.rb:52:in `perform_now'
/usr/local/bundle/gems/activejob-7.1.3.4/lib/active_job/instrumentation.rb:26:in `block in perform_now'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/railties/job_runtime.rb:13:in `block in instrument'
/usr/local/bundle/gems/activejob-7.1.3.4/lib/active_job/instrumentation.rb:40:in `block in instrument'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/notifications.rb:206:in `block in instrument'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/notifications.rb:206:in `instrument'
/usr/local/bundle/gems/activejob-7.1.3.4/lib/active_job/instrumentation.rb:39:in `instrument'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/railties/job_runtime.rb:11:in `instrument'
/usr/local/bundle/gems/activejob-7.1.3.4/lib/active_job/instrumentation.rb:26:in `perform_now'
/usr/local/bundle/gems/activejob-7.1.3.4/lib/active_job/logging.rb:18:in `block in perform_now'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/tagged_logging.rb:135:in `block in tagged'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/tagged_logging.rb:39:in `tagged'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/tagged_logging.rb:135:in `tagged'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/broadcast_logger.rb:240:in `method_missing'
/usr/local/bundle/gems/activejob-7.1.3.4/lib/active_job/logging.rb:25:in `tag_logger'
/usr/local/bundle/gems/activejob-7.1.3.4/lib/active_job/logging.rb:18:in `perform_now'
/usr/local/bundle/gems/activejob-7.1.3.4/lib/active_job/execution.rb:24:in `perform_now'
/app/app/jobs/publish_feed_job.rb:31:in `publish_apple'
/app/app/jobs/publish_feed_job.rb:18:in `block in perform'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/relation/delegation.rb:100:in `each'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/relation/delegation.rb:100:in `each'
/app/app/jobs/publish_feed_job.rb:18:in `perform'
```
