### ISSUE TITLE
Migration fails b/c user can't create uuid extension

### ISSUE THREAD

**Issue by kookster** [PRX/feeder.prx.org#202]
```
/app $ rake db:migrate RAILS_ENV=staging
Migrating to CreateEpisodeImages (20170223114125)
== 20170223114125 CreateEpisodeImages: migrating ==============================
-- create_table(:episode_images)
   -> 0.0970s
-- enable_extension("uuid-ossp")
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::InsufficientPrivilege: ERROR:  permission denied to create extension "uuid-ossp"
HINT:  Must be superuser to create this extension.
: CREATE EXTENSION IF NOT EXISTS "uuid-ossp"
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `block in exec_no_cache'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `exec_no_cache'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:584:in `execute_and_clear'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:338:in `enable_extension'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:665:in `block in method_missing'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:634:in `block in say_with_time'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:634:in `say_with_time'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:654:in `method_missing'
/app/db/migrate/20170223114125_create_episode_images.rb:20:in `up'
```

**Comment by kookster** [comment]
Solution is to log in to the db as the super user, and enable the extension.
Also need to remove the extension create and remove from the migration.

**Comment by kookster** [comment]
I have run this in staging, but not yet enabled in production.

**Comment by kookster** [comment]
Now run in production as well:
```
feeder=> create extension "uuid-ossp";
CREATE EXTENSION
```

**Comment by kookster** [comment]
PRX/feeder.prx.org#203
