### ISSUE TITLE
feedburner pings throwing errors

### ISSUE THREAD

**Issue by kookster** [PRX/feeder.prx.org#233]
noticed on twww rollout, after publishing a new version of a feed rss, would on the fixer callback throw an error trying to ping feedburner when the feedburner_url was set for the podcast. Didn't save the trace for the logs :( but should be pretty easy to reproduce using data from a twww import.

**Comment by kookster** [comment]
```
2017-05-30T15:31:12Z 12 TID-gpkquoo78 ERROR: Actor crashed!
RuntimeError: HTTP-Error: 404 Invalid path: /RPC2
/usr/local/lib/ruby/2.3.0/xmlrpc/client.rb:509:in `do_rpc'
/usr/local/lib/ruby/2.3.0/xmlrpc/client.rb:287:in `call2'
/usr/local/lib/ruby/2.3.0/xmlrpc/client.rb:268:in `call'
/app/lib/weblog_updater.rb:18:in `ping'
/app/lib/weblog_updater.rb:8:in `ping'
/app/app/models/tasks/publish_feed_task.rb:41:in `task_status_changed'
/app/app/models/task.rb:51:in `fixer_callback'
/app/app/models/task.rb:37:in `block in fixer_callback'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'
/app/app/models/task.rb:34:in `fixer_callback'
/app/app/workers/fixer_callback_worker.rb:7:in `perform'
```

**Comment by pkarman** [comment]
@kookster can you give this an estimate please?

**Comment by debenedictis** [comment]
FYI FeedBurner pings are throttled when it receives multiple pings for the same source feed in a short period of time.

**Comment by cavis** [comment]
We're moving away from feedburner, and we don't auto-ping from Feeder anymore anyways.
