### ISSUE TITLE
Check story-image status

### ISSUE THREAD

**Issue by cavis** [PRX/feeder.prx.org#313]
When creating/updating an episode from a CMS story, check the status of the image before attempting to import.  For instance, this image:

```json
{
  "prx:image": {
    "id": 610536,
    "filename": "1522032886artwork.jpg",
    "status": "not found",
    "_links": {
      "self": {
        "href": "/api/v1/stories/281025/images/610536",
        "profile": "http://meta.prx.org/model/image/story"
      },
      "profile": {
        "href": "http://meta.prx.org/model/image/story"
      },
      "enclosure": {
        "href": "https://cms.prx.org/pub/faea5d6ebb8bb3ab594bff27cd3be961/0/web/story_image/610536/medium/1522032886artwork.jpg",
        "type": "image"
      },
      "original": {
        "href": "https://cms.prx.org/pub/77f0bb2cd07e4d39c587c0bda3f7c168/0/web/story_image/610536/original/1522032886artwork.jpg",
        "type": "image"
      }
    }
  }
}
```

Results in an error that prevents _any_ updates to the episode from going through:

```
FastImage::ImageFetchFailure: FastImage::ImageFetchFailure
    from /usr/local/bundle/gems/fastimage-2.0.1/lib/fastimage.rb:205:in `rescue in initialize'
    from /usr/local/bundle/gems/fastimage-2.0.1/lib/fastimage.rb:222:in `initialize'
    from /app/app/models/concerns/image_file.rb:74:in `new'
    from /app/app/models/concerns/image_file.rb:74:in `detect_image_attributes'
```

**Comment by cavis** [comment]
This ticket is the suspenders: just have feeder ignore the bad image.  Will address CMS/Publish importer elsewhere - alert the user that the feed has a bad image.

**Comment by cavis** [comment]
No longer an issue with new Feeder UI.  And I haven't seen this on a CMS-pushed image in a long time.
