### ISSUE TITLE
Enforce a 4000 char limit for `description` when publishing to Apple API

### ISSUE THREAD

**Issue by kookster** [PRX/feeder.prx.org#850]
Either have to validate and prevent saving a description this long, or do something like truncate it to force it to meet this limit
```
"error": {
        "data": {
            "body": {
                "errors": [
                    {
                        "id": "84cb0880-8bc1-41b6-b58d-7c45689b993a",
                        "status": "409",
                        "code": "ENTITY_ERROR.ATTRIBUTE.INVALID",
                        "title": "The provided entity includes an attribute with an invalid value",
                        "detail": "Should be non-null, non-empty, and no longer than 4000 characters",
                        "source": {
                            "pointer": "/data/attributes/description"
                        }
                    }
                ]
            },
            "status": 409,
            "context": "response"
        }
    },```

**Comment by kookster** [comment]
full error message from worker log: ```
{
    "name": "shoryuken",
    "hostname": "b8bd975f9de8",
    "pid": 11,
    "level": 50,
    "time": "2023-09-21T12:50:57.322+00:00",
    "v": 0,
    "msg": "Processor failed: [\n  {\n    \"request_metadata\": {\n      \"guid\": \"prx_4548_5ec5d5cc-3916-44c4-8a0e-b6d0309c70d2\"\n    },\n    \"api_parameters\": {\n      \"data\": {\n        \"type\": \"episodes\",\n        \"attributes\": {\n          \"guid\": \"prx_4548_5ec5d5cc-3916-44c4-8a0e-b6d0309c70d2\",\n          \"title\": \"Destruction w/ Da'Shaun Harrison\",\n          \"originalReleaseDate\": \"2023-09-21T04:00:00Z\",\n          \"description\": \"<p>After 5 episodes of pontificating on weight host Ronald Young Jr. starts to truly consider what escaping from our culture of fatphobia looks like.  However through discussion with activist and writer Da’Shaun Harrison, Ronald discovers a new potential path.</p>\\n\\n<p><strong><em>Special thanks to Jon Breeding, <a href=\\\"https://www.instagram.com/sparklejams/\\\" rel=\\\"nofollow\\\" target=\\\"_blank\\\">Tracy Cox</a>, and <a href=\\\"https://dashaunharrison.com/\\\" rel=\\\"nofollow\\\" target=\\\"_blank\\\">Da’Shaun Harrison</a></em></strong></p>\\n\\n<p><strong><em>If you have a story about weight you’d like to share with us, send us an email at <a href=\\\"mailto:weight@ohitsbigron.com\\\" rel=\\\"nofollow\\\" target=\\\"_blank\\\">weight@ohitsbigron.com</a></em></strong></p>\\n\\n<p><em>Follow Ronald Young Jr. on <a href=\\\"https://twitter.com/OhitsBIGRON\\\" rel=\\\"nofollow\\\" target=\\\"_blank\\\">Twitter</a>, <a href=\\\"https://www.threads.net/@ohitsbigron\\\" rel=\\\"nofollow\\\" target=\\\"_blank\\\">Threads</a>, <a href=\\\"https://www.instagram.com/ohitsbigron/\\\" rel=\\\"nofollow\\\" target=\\\"_blank\\\">IG</a>, and <a href=\\\"https://www.tiktok.com/@ohitsbigron\\\" rel=\\\"nofollow\\\" target=\\\"_blank\\\">TikTok</a> - @ohitsbigron</em></p>\\n\\n<p>In the market for a new mattress?  Click <a href=\\\"https://shareasale.com/r.cfm?b=1187541&amp;u=3773786&amp;m=80043&amp;urllink=&amp;afftrack=\\\" rel=\\\"nofollow\\\" target=\\\"_blank\\\">this link</a> and use the code WEIGHTFORIT at checkout to get $350 off your purchase at Big Fig Mattress!</p>\\n\\n<h2>Credits</h2>\\n\\n<p>Creator/Host - Ronald Young Jr.</p>\\n\\n<p>Editor - <a href=\\\"https://www.sarahdealy.com/\\\" rel=\\\"nofollow\\\" target=\\\"_blank\\\">Sarah Dealy</a></p>\\n\\n<p>Sound Design and Mixing - <a href=\\\"https://www.starlightdiner.studio/\\\" rel=\\\"nofollow\\\" target=\\\"_blank\\\">The Reverend John Delore of Starlight Diner</a></p>\\n\\n<p>Show and Episode Art - <a href=\\\"https://www.heatherwilderart.com/\\\" rel=\\\"nofollow\\\" target=\\\"_blank\\\">Heather Wilder</a></p>\\n\\n<p>Theme music - Jey Red</p>\\n\\n<p>Additional music - Mass Potential, The Artist DT, the mysterious Breakmaster Cylinder</p>\\n\\n<h2>Additional Information</h2>\\n\\n<p>You can find out more about this show and other ohitsbigron studios shows by following us on IG @ohitsbigronstudios and on Twitter @ohitsbigronstew</p>\\n\\n<p>Check out our sister podcast television and film review show <em><a href=\\\"https://www.spreaker.com/show/leaving-the-theater\\\" rel=\\\"nofollow\\\" target=\\\"_blank\\\">Leaving the Theater</a></em>, available everywhere you listen!</p>\\n\\n<h2>Support Resources</h2>\\n\\n<p><em>If you need support for disordered eating or your body image; please check out the links below:</em></p>\\n\\n<p><a href=\\\"https://crescentcounselingva.com/\\\" rel=\\\"nofollow\\\" target=\\\"_blank\\\">Crescent Counseling Center</a></p>\\n\\n<p><a href=\\\"https://www.intuitivegrowthcounseling.com/\\\" rel=\\\"nofollow\\\" target=\\\"_blank\\\">Intuitive Growth Counseling</a></p>\\n\\n<p><a href=\\\"https://anad.org/\\\" rel=\\\"nofollow\\\" target=\\\"_blank\\\">National Association of Anorexia Nervosa and Associated disorders</a></p>\\n\\n<p><a href=\\\"https://www.theprojectheal.org/\\\" rel=\\\"nofollow\\\" target=\\\"_blank\\\">Project Heal</a></p>\\n\\n<p><a href=\\\"https://www.medainc.org/\\\" rel=\\\"nofollow\\\" target=\\\"_blank\\\">Muti-service eating disorders association</a></p>\\n\\n<p><a href=\\\"https://www.allianceforeatingdisorders.com/\\\" rel=\\\"nofollow\\\" target=\\\"_blank\\\">National Alliance for Eating Disorders</a></p>\\n\\n<p><a href=\\\"https://www.eatingrecoverycenter.com/\\\" rel=\\\"nofollow\\\" target=\\\"_blank\\\">Eating Recovery Center</a></p>\\n\\n<p><em>Or Check out some of these books;</em></p>\\n\\n<p><a href=\\\"https://bookshop.org/p/books/what-we-don-t-talk-about-when-we-talk-about-fat-aubrey-gordon/14443277\\\" rel=\\\"nofollow\\\" target=\\\"_blank\\\">What We Don’t Talk about when we talk about fat</a> - Aubrey Gordon</p>\\n\\n<p><a href=\\\"https://bookshop.org/p/books/heavy-an-american-memoir-kiese-laymon/6682101?ean=9781501125669\\\" rel=\\\"nofollow\\\" target=\\\"_blank\\\">Heavy</a> - Kiese Laymon</p>\\n\\n<p><a href=\\\"https://bookshop.org/p/books/belly-of-the-beast-the-politics-of-anti-fatness-as-anti-blackness-da-shaun-l-harrison/15663994?ean=9781623175979\\\" rel=\\\"nofollow\\\" target=\\\"_blank\\\">Belly of the Beast</a> - Da’ Shaun Harrison</p>\\n\\n<p><a href=\\\"https://bookshop.org/p/books/the-body-is-not-an-apology-the-power-of-radical-self-love-sonya-renee-taylor/7723432?ean=9781523090990\\\" rel=\\\"nofollow\\\" target=\\\"_blank\\\">The Body is Not an Apology</a> - Sonya Renee Taylor</p>\",\n          \"websiteUrl\": \"https://beta.prx.org/stories/489910\",\n          \"explicit\": false,\n          \"episodeNumber\": 6,\n          \"seasonNumber\": 1,\n          \"episodeType\": \"FULL\",\n          \"appleHostedAudioIsSubscriberOnly\": true\n        },\n        \"relationships\": {\n          \"show\": {\n            \"data\": {\n              \"type\": \"shows\",\n              \"id\": \"1686599391\"\n            }\n          }\n        }\n      }\n    },\n    \"api_url\": \"https://api.podcastsconnect.apple.com/v1/episodes\",\n    \"api_response\": {\n      \"ok\": false,\n      \"err\": true,\n      \"val\": {\n        \"data\": {\n          \"body\": {\n            \"errors\": [\n              {\n                \"id\": \"3b4008bd-47fe-45e9-b232-23c49fea058f\",\n                \"status\": \"409\",\n                \"code\": \"ENTITY_ERROR.ATTRIBUTE.INVALID\",\n                \"title\": \"The provided entity includes an attribute with an invalid value\",\n                \"detail\": \"Should be non-null, non-empty, and no longer than 4000 characters\",\n                \"source\": {\n                  \"pointer\": \"/data/attributes/description\"\n                }\n              }\n            ]\n          },\n          \"status\": 409,\n          \"context\": \"response\"\n        }\n      },\n      \"_stack\": \"    at formatApiError (file:///var/task/api_response.js:36:12)\\n    at file:///var/task/api.js:131:46\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\"\n    }\n  }\n]\n"
}```

**Comment by kookster** [comment]
and the stack trace
```
{
    "name": "shoryuken",
    "hostname": "b8bd975f9de8",
    "pid": 11,
    "level": 50,
    "time": "2023-09-21T12:50:57.323+00:00",
    "v": 0,
    "msg": "/app/app/models/apple/api.rb:270:in `raise_bridge_api_error'\n/app/app/models/apple/api.rb:264:in `bridge_remote_and_retry!'\n/app/app/models/apple/episode.rb:85:in `create_episodes'\n/app/app/models/apple/publisher.rb:178:in `block in sync_episodes!'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:99:in `block in tagged'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:37:in `tagged'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:99:in `tagged'\n/app/app/models/apple/publisher.rb:168:in `sync_episodes!'\n/app/app/models/apple/publisher.rb:93:in `block (2 levels) in publish!'\n/app/app/models/apple/publisher.rb:91:in `each'\n/app/app/models/apple/publisher.rb:91:in `each_slice'\n/app/app/models/apple/publisher.rb:91:in `block in publish!'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:99:in `block in tagged'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:37:in `tagged'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:99:in `tagged'\n/app/app/models/apple/publisher.rb:90:in `publish!'\n/app/app/jobs/publish_apple_job.rb:5:in `publish_to_apple'\n/app/app/jobs/publish_apple_job.rb:14:in `perform'\n/usr/local/bundle/gems/activejob-7.0.8/lib/active_job/execution.rb:65:in `block in _perform_job'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:118:in `block in run_callbacks'\n/usr/local/bundle/gems/newrelic_rpm-8.13.1/lib/new_relic/agent/instrumentation/active_job.rb:54:in `perform'\n/usr/local/bundle/gems/newrelic_rpm-8.13.1/lib/new_relic/agent/instrumentation/active_job.rb:23:in `block (4 levels) in <main>'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:127:in `instance_exec'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:127:in `block in run_callbacks'\n/usr/local/bundle/gems/i18n-1.14.1/lib/i18n.rb:317:in `with_locale'\n/usr/local/bundle/gems/activejob-7.0.8/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:127:in `instance_exec'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:127:in `block in run_callbacks'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/core_ext/time/zones.rb:65:in `use_zone'\n/usr/local/bundle/gems/activejob-7.0.8/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:127:in `instance_exec'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:127:in `block in run_callbacks'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:138:in `run_callbacks'\n/usr/local/bundle/gems/activejob-7.0.8/lib/active_job/execution.rb:64:in `_perform_job'\n/usr/local/bundle/gems/activejob-7.0.8/lib/active_job/instrumentation.rb:20:in `_perform_job'\n/usr/local/bundle/gems/activejob-7.0.8/lib/active_job/execution.rb:52:in `perform_now'\n/usr/local/bundle/gems/activejob-7.0.8/lib/active_job/instrumentation.rb:14:in `block in perform_now'\n/usr/local/bundle/gems/activejob-7.0.8/lib/active_job/instrumentation.rb:25:in `block in instrument'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/notifications.rb:206:in `block in instrument'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/notifications/instrumenter.rb:24:in `instrument'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/notifications.rb:206:in `instrument'\n/usr/local/bundle/gems/activejob-7.0.8/lib/active_job/instrumentation.rb:35:in `instrument'\n/usr/local/bundle/gems/activejob-7.0.8/lib/active_job/instrumentation.rb:14:in `perform_now'\n/usr/local/bundle/gems/activejob-7.0.8/lib/active_job/logging.rb:18:in `block in perform_now'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:99:in `block in tagged'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:37:in `tagged'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:99:in `tagged'\n/usr/local/bundle/gems/activejob-7.0.8/lib/active_job/logging.rb:25:in `tag_logger'\n/usr/local/bundle/gems/activejob-7.0.8/lib/active_job/logging.rb:18:in `perform_now'\n/usr/local/bundle/gems/activejob-7.0.8/lib/active_job/execution.rb:24:in `perform_now'\n/app/app/jobs/publish_feed_job.rb:36:in `block in publish_apple'\n/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/relation/delegation.rb:88:in `each'\n/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/relation/delegation.rb:88:in `each'\n/app/app/jobs/publish_feed_job.rb:34:in `map'\n/app/app/jobs/publish_feed_job.rb:34:in `publish_apple'\n/app/app/jobs/publish_feed_job.rb:29:in `publish_feed'\n/app/app/jobs/publish_feed_job.rb:18:in `block in perform'\n/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/relation/delegation.rb:88:in `each'\n/usr/local/bundle/gems/activerecord-7.0.8/lib/active_record/relation/delegation.rb:88:in `each'\n/app/app/jobs/publish_feed_job.rb:18:in `perform'\n/usr/local/bundle/gems/activejob-7.0.8/lib/active_job/execution.rb:65:in `block in _perform_job'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:118:in `block in run_callbacks'\n/usr/local/bundle/gems/newrelic_rpm-8.13.1/lib/new_relic/agent/tracer.rb:104:in `in_transaction'\n/usr/local/bundle/gems/newrelic_rpm-8.13.1/lib/new_relic/agent/instrumentation/active_job.rb:70:in `run_in_transaction'\n/usr/local/bundle/gems/newrelic_rpm-8.13.1/lib/new_relic/agent/instrumentation/active_job.rb:56:in `perform'\n/usr/local/bundle/gems/newrelic_rpm-8.13.1/lib/new_relic/agent/instrumentation/active_job.rb:23:in `block (4 levels) in <main>'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:127:in `instance_exec'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:127:in `block in run_callbacks'\n/usr/local/bundle/gems/i18n-1.14.1/lib/i18n.rb:322:in `with_locale'\n/usr/local/bundle/gems/activejob-7.0.8/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:127:in `instance_exec'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:127:in `block in run_callbacks'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/core_ext/time/zones.rb:65:in `use_zone'\n/usr/local/bundle/gems/activejob-7.0.8/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:127:in `instance_exec'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:127:in `block in run_callbacks'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:138:in `run_callbacks'\n/usr/local/bundle/gems/activejob-7.0.8/lib/active_job/execution.rb:64:in `_perform_job'\n/usr/local/bundle/gems/activejob-7.0.8/lib/active_job/instrumentation.rb:20:in `_perform_job'\n/usr/local/bundle/gems/activejob-7.0.8/lib/active_job/execution.rb:52:in `perform_now'\n/usr/local/bundle/gems/activejob-7.0.8/lib/active_job/instrumentation.rb:14:in `block in perform_now'\n/usr/local/bundle/gems/activejob-7.0.8/lib/active_job/instrumentation.rb:25:in `block in instrument'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/notifications.rb:206:in `block in instrument'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/notifications/instrumenter.rb:24:in `instrument'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/notifications.rb:206:in `instrument'\n/usr/local/bundle/gems/activejob-7.0.8/lib/active_job/instrumentation.rb:35:in `instrument'\n/usr/local/bundle/gems/activejob-7.0.8/lib/active_job/instrumentation.rb:14:in `perform_now'\n/usr/local/bundle/gems/activejob-7.0.8/lib/active_job/logging.rb:18:in `block in perform_now'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:99:in `block in tagged'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:37:in `tagged'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/tagged_logging.rb:99:in `tagged'\n/usr/local/bundle/gems/activejob-7.0.8/lib/active_job/logging.rb:25:in `tag_logger'\n/usr/local/bundle/gems/activejob-7.0.8/lib/active_job/logging.rb:18:in `perform_now'\n/usr/local/bundle/gems/activejob-7.0.8/lib/active_job/execution.rb:30:in `block in execute'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:118:in `block in run_callbacks'\n/usr/local/bundle/gems/activejob-7.0.8/lib/active_job/railtie.rb:54:in `block (4 levels) in <class:Railtie>'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/execution_wrapper.rb:92:in `wrap'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/reloader.rb:72:in `block in wrap'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/execution_wrapper.rb:92:in `wrap'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/reloader.rb:71:in `wrap'\n/usr/local/bundle/gems/activejob-7.0.8/lib/active_job/railtie.rb:53:in `block (3 levels) in <class:Railtie>'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:127:in `instance_exec'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:127:in `block in run_callbacks'\n/usr/local/bundle/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:138:in `run_callbacks'\n/usr/local/bundle/gems/activejob-7.0.8/lib/active_job/execution.rb:28:in `execute'\n/usr/local/bundle/gems/shoryuken-6.0.0/lib/shoryuken/extensions/active_job_adapter.rb:88:in `perform'\n/usr/local/bundle/gems/shoryuken-6.0.0/lib/shoryuken/processor.rb:21:in `block (2 levels) in process'\n/usr/local/bundle/gems/shoryuken-6.0.0/lib/shoryuken/middleware/chain.rb:98:in `block in invoke'\n/usr/local/bundle/gems/shoryuken-6.0.0/lib/shoryuken/middleware/server/active_record.rb:6:in `call'\n/usr/local/bundle/gems/shoryuken-6.0.0/lib/shoryuken/middleware/chain.rb:100:in `block in invoke'\n/usr/local/bundle/gems/shoryuken-6.0.0/lib/shoryuken/middleware/server/auto_extend_visibility.rb:10:in `call'\n/usr/local/bundle/gems/shoryuken-6.0.0/lib/shoryuken/middleware/chain.rb:100:in `block in invoke'\n/usr/local/bundle/gems/shoryuken-6.0.0/lib/shoryuken/middleware/server/auto_delete.rb:6:in `call'\n/usr/local/bundle/gems/shoryuken-6.0.0/lib/shoryuken/middleware/chain.rb:100:in `block in invoke'\n/usr/local/bundle/gems/shoryuken-6.0.0/lib/shoryuken/middleware/server/exponential_backoff_retry.rb:8:in `call'\n/usr/local/bundle/gems/shoryuken-6.0.0/lib/shoryuken/middleware/chain.rb:100:in `block in invoke'\n/usr/local/bundle/gems/shoryuken-6.0.0/lib/shoryuken/middleware/server/timing.rb:12:in `call'\n/usr/local/bundle/gems/shoryuken-6.0.0/lib/shoryuken/middleware/chain.rb:100:in `block in invoke'\n/usr/local/bundle/gems/shoryuken-6.0.0/lib/shoryuken/middleware/chain.rb:103:in `invoke'\n/usr/local/bundle/gems/shoryuken-6.0.0/lib/shoryuken/processor.rb:20:in `block in process'\n/usr/local/bundle/gems/shoryuken-6.0.0/lib/shoryuken/logging.rb:20:in `with_context'\n/usr/local/bundle/gems/shoryuken-6.0.0/lib/shoryuken/processor.rb:19:in `process'\n/usr/local/bundle/gems/shoryuken-6.0.0/lib/shoryuken/processor.rb:8:in `process'\n/usr/local/bundle/gems/shoryuken-6.0.0/lib/shoryuken/manager.rb:100:in `block in assign'\n/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'\n/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `block in synchronize'\n/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'\n/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'\n/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:22:in `execute'\n/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/promise.rb:564:in `block in realize'\n/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `run_task'\n/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:343:in `block (3 levels) in create_worker'\n/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `loop'\n/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block (2 levels) in create_worker'\n/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `catch'\n/usr/local/bundle/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `block in create_worker'"
}
```
